### ISSUE TITLE
Crate depends on non-public implementation details of `syn`

### ISSUE THREAD

**Issue by cole-miller** [foresterre/parameterized#36]
In `syn` versions `<= 1.0.57`, the `syn::export` module is `pub` (i.e. you can import it) but documented as being an implementation detail that's not considered part of the public API. `syn v1.0.58` reinforces this by moving the module to a new path, `syn::__private`: https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7. Because this crate makes use of `syn::export` it will not build with the latest `syn` (confirmed by checking out the repo and running `cargo build`).

**Comment by foresterre** [comment]
Thanks for letting me know about this issue 😄.
It should be fixed in #37.
