### ISSUE TITLE
Can't use new `indexmap` when using `parametereized`

### ISSUE THREAD

**Issue by tsnoam** [foresterre/parameterized#56]
Hello,

I have a project which uses `parameterized` as a dev dependency.
I wanted to add a dependency on `indexmap` to my project, and wanted to used the latest version of it. But this is the error I get from cargo:

```
   ... which satisfies dependency `indexmap = "=1.6.2"` of package `parameterized-macro v1.0.0`
    ... which satisfies dependency `parameterized-macro = "^1"` of package `parameterized v1.0.0`
    ... which satisfies dependency `parameterized = "^1.0"` of package `MYPROJECT v0.1.0 (/path/to/MYPROJECT)`
```

I was wondering what is the reason for locking `parameterized-macro` on version 1.6.

I searched the repository and found a reference that it was due to a security consideration, but what it was was never mentioned. Also, it had been over a year since, it might have been resolved.

I also saw some mentions of you don't want to raise the MSVP, which is ok, but I thought maybe there's a middleground here?

AFAIK, if changing the dependency to `indexmap = "1.6.2"` (without the limiting `=`), I think that cargo will be able to coalesce the dependencies into 1.9 (on my case).

**Comment by foresterre** [comment]
Hi, thanks for reporting this. I would be happy to try this middle ground :)!

**Comment by tsnoam** [comment]
Thanks @foresterre 
That was the quickest response I've seen, highly appreciated!

Will you upload a new version to crates.io soon?

**Comment by foresterre** [comment]
The update is now available from [crates.io](https://crates.io/crates/parameterized-macro/1.0.1). It should be pulled in [automagically](https://github.com/foresterre/parameterized/blob/0a469a28d70ae28ea16416b93615e2a7ef139d26/Cargo.toml#L18) by parameterized, assuming its not freezed by your lock file.
