### ISSUE TITLE
Return type is not variable

### ISSUE THREAD

**Issue by wackazong** [foresterre/parameterized#75]
Parameterized seems to assume that the test function has no return value. Some people, including me, use `anyhow::Result<()>` as return type, in order to be able to use the question mark operator throughout the test. This does not seem to be compatible with Parameterized.

Would be great if Parameterized works with this return type.

**Comment by foresterre** [comment]
Released in [parameterized 1.1.0](https://crates.io/crates/parameterized/1.1.0)

**Comment by foresterre** [comment]
Thanks for the request!
