### ISSUE TITLE
#[tokio::test] support

### ISSUE THREAD

**Issue by Tockra** [foresterre/parameterized#80]
Hey,

do you plan #[tokio::test] support ?

T

**Comment by foresterre** [comment]
That shouldn't be too difficult to add. What syntax would you expect? It can also be a separate attribute like:

```
#[parameterized(....)]
#[parameterized_macro(tokio::test)] // this is more generic, so could support any test attribute
```

Or

```
#[parameterized(....)]
#[tokio::test] // this is more specific, and would require support for each test attribute separately 
```

**Comment by Tockra** [comment]
I've no prefered solution. 
I'm just here and want to parametrize some tokio tests ;) 
Hopefully this works in near future
